rtx.localtonemap.exposurePreferenceSigma = 3.0
rtx.localtonemap.highlights = 3.2
rtx.tonemap.exposureBias = 0.173
rtx.localtonemap.shadows = 2.4
rtx.localtonemap.exposurePreferenceOffset = -0.004
rtx.userBrightness.userBrightness = 45
rtx.localtonemap.exposure = 0.42
rtx.tonemap.finalizeWithACES = True
rtx.tonemappingMode = 1
rtx.localtonemap.finalizeWithACES = True
